[global]

# Production mode settings
developmentMode = false
dataFrameSerialization = "legacy"

[logger]

# Production logging level
level = "warning"

[client]

# Navigation settings
showSidebarNavigation = true
showErrorDetails = false
toolbarMode = "minimal"

[server]

# Production server settings
port = 8501
address = "localhost"
headless = true
maxUploadSize = 50
maxMessageSize = 50

# Security settings
enableWebsocketCompression = true
enableCORS = false
enableXsrfProtection = true
allowRunOnSave = false

# Performance settings
runOnSave = false
fileWatcherType = "none"

[browser]

# Internet address where users should point their browsers in order to connect to the app.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

[theme]

# The preset Streamlit theme that your custom theme inherits from.
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#FF6B6B"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app.
font = "sans serif"