[global]

# Development mode settings
developmentMode = true

[logger]

# Development logging level
level = "info"

[client]

# Navigation settings
showSidebarNavigation = true
showErrorDetails = true
toolbarMode = "developer"

[server]

# Development server settings
address = "localhost"
headless = false
maxUploadSize = 50
maxMessageSize = 50

# Security settings (relaxed for development)
enableWebsocketCompression = true
enableCORS = false
enableXsrfProtection = true
allowRunOnSave = true

# Development performance settings
runOnSave = true
fileWatcherType = "auto"

[browser]

# Internet address where users should point their browsers in order to connect to the app.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

[theme]

# The preset Streamlit theme that your custom theme inherits from.
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#FF6B6B"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app.
font = "sans serif"